server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  datasource:
    url: jdbc:h2:mem:customer;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL  # In-memory H2 database
    driver-class-name: org.h2.Driver
    username: sa  # Default H2 username
    password: password  # Default H2 password
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop # Automatically create/update schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
